services:
  terminal.subscriber_kernel:
    class: features.terminal.kernel.KernelEventSubscriber
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.subscriber: ~

