services:
  statistic.subscriber_gui:
    class: src.statistic.kernel.AppListener
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.listener:
         - { name: 'window.tab', method: 'OnTab', priority: 2 }
         - { name: 'window.tab_switch', method: 'OnTabSwitched', priority: 1 }
    