services:
  clipboard.listener.app:
    class: src.clipboard.kernel.AppListener
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.listener:
         - { name: 'kernel_event.stop', method: 'OnStop', priority: 0 }
         - { name: 'kernel_event.window_toggle_scanning', method: 'OnScaningSwitch', priority: 0 }
         - { name: 'kernel_event.window_tab', method: 'OnTab', priority: 0 }
         