services:
  dictionary_converter:
    class: features.converter.service.DictionaryConverter
  convertor.subscriber_kernel:
    class: features.converter.kernel.KernelEventSubscriber
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.subscriber: ~

