services:
  dbus_service.kernel_subscriber:
    class: src.dbus_service.kernel.AppListener
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.listener:
         - { name: 'kernel.start', method: 'OnStart', priority: -128 }
         