services:
  dbus_service.kernel_subscriber:
    class: features.dbus_service.kernel.KernelEventSubscriber
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.subscriber: ~
