services:
  icon.subscriber_gui:
    class: src.linux_icon.kernel.AppListener
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.listener:
         - { name: 'kernel_event.window', method: 'OnWindow', priority: 0 }

