services:
  dictionary:
    class: features.dictionary.service.DictionaryManager
    arguments:
      - ["./dictionaries/*.dat"]
  dictionary.subscriber_gui:
    class: features.dictionary.kernel.KernelEventSubscriber
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.subscriber: ~
