services:
  popup.subscriber_dictionary:
    class: src.popup.dictionary.AppListener
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.listener:
         - { name: 'kernel_event.window_clipboard', method: 'OnClipboard', priority: 10 }
         - { name: 'kernel_event.window_translate_all', method: 'OnTranslateAll', priority: 10 }
