services:
  clipboard.subscriber_gui:
    class: features.clipboard.kernel.KernelEventSubscriber
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.subscriber: ~
