services:
  dictionary_converter:
    class: src.converter.service.DictionaryConverter
  converter.subscriber_kernel:
    class: src.converter.kernel.AppListener
    calls:
         - [ set_container, [ "@service_container" ]]
    tags:
        event.listener:
         - { name: 'kernel_event.window_tab', method: 'OnTab', priority: 5 }

